#!/usr/bin/perl -w

while ($line = <STDIN>) {
    chomp $line;
    if (substr($line,0,1) eq '>') {
	print "\n" . substr($line,1) . "\t" if substr($line,0,1) eq '>';
    }
    else {
	print $line;
    }
}
print "\n";
